# Generated by Django 5.1.1 on 2026-07-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_contenedor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase de icono FontAwesome, ej: fa-gem, fa-ring', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Todos'), ('mujer', 'Mujer'), ('hombre', 'Hombre'), ('niño', 'Niño'), ('niña', 'Niña'), ('unisex', 'Unisex')], max_length=20, null=True),
        ),
    ]
