# Generated by Django 5.1.1 on 2026-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_agregar_icono_categoria_genero_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='icono',
        ),
    ]
