# Generated by Django 5.1.1 on 2026-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_quitar_icono_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
