# Generated by Django 5.0.14 on 2026-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_categoria_foto_producto_en_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_unidad_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Precio unidad oferta'),
        ),
    ]
