# Generated by Django 5.0.14 on 2026-08-12 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0018_producto_precio_unidad_oferta'),
        ('usuarios', '0006_perfilusuario_comision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad reservada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='productos.producto', verbose_name='Producto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_registradas', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='usuarios.perfilusuario', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Reserva de producto',
                'verbose_name_plural': 'Reservas de productos',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', max_length=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del pago')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/reservas/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_reservas_registrados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.reservaproducto', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pago de reserva',
                'verbose_name_plural': 'Pagos de reservas',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
