# Generated by Django 5.0.14 on 2026-08-13 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_producto_precio_unidad_oferta'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaproducto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='reservaproducto',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='reservaproducto',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='reservaproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='pagoreserva',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='descuento_tipo',
            field=models.CharField(choices=[('ninguno', 'Sin descuento'), ('fijo', 'Monto fijo'), ('porcentaje', 'Porcentaje')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='descuento_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR')], default='efectivo', max_length=20),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservaproducto',
            name='tipo_pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservaproducto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ReservaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('modalidad', models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('mayor', 'Mayor')], default='unidad', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservas.reservaproducto')),
            ],
            options={
                'verbose_name': 'Item de reserva',
                'verbose_name_plural': 'Items de reserva',
            },
        ),
    ]
