# Generated by Django 5.0.14 on 2026-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reservaproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaproducto',
            name='inventario_tipo',
            field=models.CharField(choices=[('tienda', 'Tienda'), ('deposito', 'Depósito')], default='tienda', max_length=20, verbose_name='Inventario usado'),
        ),
    ]
