# Generated by Django 5.2.17 on 2026-09-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reservaitem_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaitem',
            name='modalidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('mayor', 'Mayor'), ('oferta', 'Oferta')], default='unidad', max_length=20),
        ),
    ]
