# Generated by Django 5.0.14 on 2026-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_alter_tienda_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono/Celular'),
        ),
    ]
