# Generated by Django 5.0.14 on 2026-08-08 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0018_producto_precio_unidad_oferta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('moneda', models.CharField(choices=[('BOB', 'Bolivianos'), ('USD', 'Dólares')], default='BOB', max_length=10)),
                ('tipo_cambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_tipo', models.CharField(choices=[('ninguno', 'Sin descuento'), ('fijo', 'Monto fijo'), ('porcentaje', 'Porcentaje')], default='ninguno', max_length=20)),
                ('descuento_valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_elaboracion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-fecha_elaboracion'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('modalidad', models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('mayor', 'Mayor')], default='unidad', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proformas.proforma')),
            ],
            options={
                'verbose_name': 'Item de Proforma',
                'verbose_name_plural': 'Items de Proforma',
            },
        ),
    ]
