# Generated by Django 5.0.14 on 2026-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='nit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
