# Generated by Django 5.2.17 on 2026-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proformas', '0004_alter_proformaitem_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaitem',
            name='modalidad',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('mayor', 'Mayor'), ('oferta', 'Oferta')], default='unidad', max_length=20),
        ),
    ]
