# Generated by Django 5.1.1 on 2026-07-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('qr', 'QR'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, null=True),
        ),
    ]
