# Generated by Django 5.0.14 on 2026-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(blank=True, choices=[('tienda', 'Venta en Tienda'), ('delivery', 'Delivery'), ('envio_departamento', 'Envío a otro departamento')], default='tienda', max_length=30, null=True),
        ),
    ]
